### ISSUE TITLE
Housekeeping uses webserver for assets instead of cdn

### ISSUE THREAD

**Issue by GitHabbo** [Quackster/Havana#14]
The housekeeping currently loads assets in from the webserver, but they are also available on the cdn.
e.g.: 
* https://classichabbo.com/public/hk/css/bootstrap.min.css
* https://cdn.classichabbo.com/public/hk/css/bootstrap.min.css

**Comment by Quackster** [comment]
> Yeah that "CDN" isn't really supposed to be used by everyone.

I'm confused, classichabbo uses it, what's the problem?

**Comment by emansom** [comment]
> I'm confused, classichabbo uses it, what's the problem?

Potentially ridiculous bandwidth utilization as some spanish/brazil kept the defaults. It's your call however. 🤷🏻

**Comment by Quackster** [comment]
Pull request has been merged that resolves this.
