### ISSUE TITLE
Housekeeping response time on Bans page

### ISSUE THREAD

**Issue by GitHabbo** [Quackster/Havana#16]
When there's a lot of bans inside the `user_bans` table, the Bans page in the Housekeeping takes a long time to load.
This could be solved by implementing pagination in the same way it is done on the dashboard (player overview).

## Testing with *1375* bans
(Empty cache and hard reload)
1. 21.17s
2. 14.92s
3. 13.74s
4. 14.35s
5. 14.25s

avg: 15.69s

**Comment by emansom** [comment]
Or doing all database reads in one big transaction. Should reduce it to less than <100ms.

**Comment by Quackster** [comment]
Resolved with pull request: https://github.com/Quackster/Havana/pull/17
