### ISSUE TITLE
Housekeeping avatar imager stopped working

### ISSUE THREAD

**Issue by GitHabbo** [Quackster/Havana#20]
In the housekeeping, avatar images get loaded in with the habbo.com.tr domain, but it seems as they just deleted that endpoint. All images are returning 404's now.

Replacing it with the imager used for the regular site would fix this.

**Comment by GitHabbo** [comment]
They seem to have put it back online.

But changing to the internal imager would still be best practice imo.

**Comment by Quackster** [comment]
Addressed in this commit. 90e2cc717d5242604809f572908b5e06e7e7da45
