### ISSUE TITLE
room_ads entry for Space Cafe is set to billboard_idol_02.gif, file included in havana_www has the .png extension 

### ISSUE THREAD

**Issue by PolybianPrime** [Quackster/Havana#3]
Will only show an empty black billboard if this is not accounted for.

**Comment by Quackster** [comment]
Yeah the havana_www.zip is going to be updated in future when I move to the joystick implementation, and I'll be sure to make sure this issue gets fixed when updating it. See, https://github.com/Quackster/Havana/issues/1

**Comment by Quackster** [comment]
[billboards.zip](https://github.com/Quackster/Havana/files/9488252/billboards.zip)
For now, just use this.
