### ISSUE TITLE
Change looks template doesn't properly replace the imaging path on wardrobe figures

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Havana#31]
![image](https://user-images.githubusercontent.com/6492427/212904370-dd5e0897-6689-4fad-8e07-86af6ace6d8a.png)

`ProfileController.java:144`

**Comment by Quackster** [comment]
Thank you! Will be fixed next time I merge `develop` to `master` - commit is [here](https://github.com/Quackster/Havana/commit/310714392417e433193d3abcef35b9f5097f9cf5).

**Comment by Quackster** [comment]
Fixed and released: https://github.com/Quackster/Havana/releases/tag/release-22012019
