### ISSUE TITLE
Captcha not showing. Unable to create account.

### ISSUE THREAD

**Issue by crusader290** [Quackster/Havana#32]
Hey there, even with font-manager installed I am unable to see the captcha on my registration page.

(I am running this on Ubuntu Server (headless) )

Is there a quick way I can disable the captcha system on the register page?

also could I possibly get an example of a row in the user table?

**Comment by crusader290** [comment]
![firefox_mpZrBfmkBf](https://user-images.githubusercontent.com/59276425/217403071-b5d9f8b5-9bde-4e28-ab2c-528f81051d92.png)
Nevermind. Im an idiot. 

For future reference you can find this setting in register,tpl

**Comment by Quackster** [comment]
Can you please post the error logs when the captcha isn't visible?

**Comment by crusader290** [comment]
Sorry, I deleted the project. 
The web server kept crashing for me whenever I tried to register an account.
I'll have to try this on a fresh install when I get the chance.

**Comment by Quackster** [comment]
The web server shouldn't crash. Are you sure your version is up to date? 

https://github.com/Quackster/Havana/releases/tag/release-23012023

**Comment by crusader290** [comment]
I will check again soon.
It may have had something to do with me replacing "localhost" with my local IP in the havana.sql. This was done so that I could connect from other computers in my network. If this wasn't the right move I'd appreciate some advice on the correct way to do this.

**Comment by crusader290** [comment]
Tried this again on windows (without changing the default havana.sql) and can confirm captcha doesn't show and web server appears to hang/crash on registration page.

**Comment by crusader290** [comment]
No errors present in logs.
