### ISSUE TITLE
Webserver crashes after 30 seconds.

### ISSUE THREAD

**Issue by crusader290** [Quackster/Havana#33]
Tried this on both linux and windows with no modications to the server files and can confirm the web server appears to crash/hang after 30 seconds.

No errors present in logs.

**Comment by Quackster** [comment]
Yes, I fixed this. 

The fix was that it tried to resolve the imager even when its offline causing the server to hang - here https://github.com/Quackster/Havana/commit/4e350d416f060acd8d2479badc26222c31b5f843.

I will ask again - since you did not respond before, are you using the latest release?

**Comment by crusader290** [comment]
Yes I am using the latest release.

**Comment by Quackster** [comment]
Can you change the "site.imaging.path" in settings to a value like ``https://habbo.com`` and see if it still happens

**Comment by crusader290** [comment]
> Can you change the "site.imaging.path" in settings to a value like `https://habbo.com` and see if it still happens

Where is this setting located?

**Comment by crusader290** [comment]
> Can you change the "site.imaging.path" in settings to a value like `https://habbo.com` and see if it still happens

Its working now. 
Can you explain how changing that setting has made it work?

**Comment by Quackster** [comment]
Well, what was the setting before?

If it was http://localhost:5000 (by default) **and** you were using the latest Havana release then it still should've worked without causing the server to hang - except that the imager would've been offline.

**Comment by crusader290** [comment]
It was originally just http://localhost
No port number was specified.
I can confirm that I was using "Release - 23/01/2023"

**Comment by Quackster** [comment]
With all due respect, that doesn't make sense because the server originally creates it with port number 5000, as indicated here. 

https://github.com/Quackster/Havana/blob/master/Havana-Web/src/main/java/org/alexdev/http/util/config/WebSettingsConfigWriter.java#L17

**Comment by crusader290** [comment]
I understand how ever I have tried this on 2 different computers with a fresh "Release - 23/01/2023" and the outcome is the same. 

By the looks of it the settings aren't properly being pushed to the database as I can see minor differences between some of the settings values shown in [WebSettingsConfigWriter.java](https://github.com/Quackster/Havana/blob/master/Havana-Web/src/main/java/org/alexdev/http/util/config/WebSettingsConfigWriter.java#L17) and the my current Database (Post Initial Server Run).

**Comment by Quackster** [comment]
So the issue was that havana.sql wasn't a clean database, and still had old ``settings`` table values in there. 

Which meant http://localhost:5000 for ``site.imaging.path`` was always going to end up as http://localhost (which is very bad...)

I've also now changed the key to ``site.imaging.endpoint`` (to indicate that it's an endpoint to an imager such as [Minerva](https://github.com/Quackster/Minerva))
