### ISSUE TITLE
Trax is Buggy and Causes Crashes

### ISSUE THREAD

**Issue by admiralspeedy** [Quackster/Havana#34]
Set this up quickly to fool around in and I noticed that Trax is very buggy and causes crashes.

I crashed out of the hotel probably half a dozen times last night in the course of about 3 hours playing around with Trax (I'm using the recommended Basilisk Portable). A few of the crashes were Shockwave crashing, others just took me right to the connection error page. The server does not appear to log any errors when this happens (none that I can see in the terminal or in the log files).

Another issue I noticed, and it may be just an issue that was in the original game, but sometimes you can click through the Trax editor and end up leaving your room, which closes the editor and loses anything you haven't saved yet. Also, a few of the sound packs have duplicate sounds or sounds that don't work.

**Comment by Quackster** [comment]
This is an issue with Shockwave itself and not my server. Note: it never happens when running the Habbo client within a projector.
