### ISSUE TITLE
[Request] A video tutorial on how to get this set up along with Minerva

### ISSUE THREAD

**Issue by deeyonn** [Quackster/Havana#35]
Hi, I'm interested to host this as a pet project for me and my friends, and have been looking at many other releases. However hosting a hotel seems to be a very complicated procedure, unable to get nitro working etc. So this release appeals to me the most. 

I'm kinda lost when following the instructions on the main page. Do you think you could make a quick video on how to get a server set up using IIS or some other cloud hosting like Google Cloud or AWS?

**Comment by deeyonn** [comment]
I got it working on localhost. I'm not sure what Minerva does so an explanation would help!

**Comment by Quackster** [comment]
> I got it working on localhost. I'm not sure what Minerva does so an explanation would help!

Minerva is an imager. It turns Habbo figure codes into a .png to render them for the websites. Same goes for groups but for group badges.

Minerva is optional, but without it, none of your Habbos or group badges will be able to be displayed throughout the website.

**Comment by deeyonn** [comment]
Thank you for the information! There are many terms to learn about retro hosting, I'm glad I got one out of the way.
