### ISSUE TITLE
Teleporters have unpredictable behavior at times

### ISSUE THREAD

**Issue by jtieri** [Quackster/Havana#40]
When I first setup Havana a few months ago I lightly tested the teleporters and everything seemed to be working correctly. This week we have had ~6 concurrent users online poking around and looking for issues and we realized that teleporters can have very unpredictable behavior. 

All issues described below happen on the current main branch and were observed when the linked teleporters are in two different rooms.
- Sometimes you can enter a teleporter, it will take you to the linked tele in another room but you won't be able to exit the tele.
- Sometimes you can enter a teleporter, it will take you to the room the linked tele is in but you just appear at a random tile in the room instead of walking out of the tele. I've even seen it where you go to the room the linked tele is in but your avatar enters the room from the door.
- Sometimes teleporters just don't do anything, you walk in and nothing happens.

I tried to reproduce some of these behaviors when the linked teleporters are in the same room and they appeared to work fine in that case, or at least I was not able to reproduce the errors.

When these issues happen there are no error logs in the server. Additionally sometimes they still work completely fine, it's very unpredictable and not always easy to reproduce. I will try to gather some logs this weekend as well as some screen recordings that demonstrate some of the behaviors mentioned above.

Server is running on Ubuntu 20.04 using the latest main branch. Issues can be observed while using both Basilisk portable browser as well as a Shockwave projector.

**Comment by Quackster** [comment]
Tried to address with commit: 2ccae8c7ef70f79f01f59fcbbe324d78266fd472

If it keeps happening, re-open the issue.
