### ISSUE TITLE
localhost cms issue

### ISSUE THREAD

**Issue by Nizero-cmd** [Quackster/Havana#42]
I've changed localhost ip mostly everywhere in the source folder with my custom ip, the cms is reachable but every scripts continue to point to localhost ending up with no images and no working login when accessing from another pc in the same lan

**Comment by JorgeEspadas** [comment]
How did you solve this?

**Comment by Quackster** [comment]
> How did you solve this?

The setting is in the `settings` table under setting `static.content.path`.
