### ISSUE TITLE
[FEATURE REQUEST] Docker container install

### ISSUE THREAD

**Issue by Cuphead74832** [Quackster/Havana#49]
I wish there was a docker container that i could just pull and run the Server. This would also allow múltiple Server instantes a long with making backup and restore and migrations way easier.

**Comment by emansom** [comment]
Agreed. Used to maintain some.

**Comment by Quackster** [comment]
I have no interest in creating a Docker install, but if anybody wants to pull request to add a Dockerfile, feel free to do so and I will review it and add it.

**Comment by arths31** [comment]
There you go guys, #50
