### ISSUE TITLE
Welcome Lounge bot Harry text outside of chat bubble

### ISSUE THREAD

**Issue by PolybianPrime** [Quackster/Havana#5]
One of Harry's responses when you say his name is "Hello and welcome to Habbo Hotel! Enjoy your stay :)". This text does not stay inside the chat bubble but hangs low inside and under it. Screenshot here: https://imgur.com/a/mnz5kyJ

Could be a Basilisk issue, not sure.

**Comment by Quackster** [comment]
Fixed. https://github.com/Quackster/Havana/commit/7947fbcb5320350da9cb698d70f48a3a300d2a91
