### ISSUE TITLE
Flash update: Mod Tool / Chat is a bit bugged

### ISSUE THREAD

**Issue by Kaan2106** [Quackster/Havana#53]
I tested every help option (including reporting a specific user and their many options) of the flash-client and none of them get sent to the server / database.

If the reporting user is on the old client the entry will be made, and displayed to a mod - but only if the mod is on the old-client also.
If a mod uses the flash-client there will be nothing.

Example:
![grafik](https://github.com/user-attachments/assets/66ac3289-a13e-4b0a-8629-03f2a030bd80)
(Yeah I used a modified version of havana, but this bug also happens in the original havana release)

Secondary: a user can ignore / shutup a staff member, which should not be possible:
![grafik](https://github.com/user-attachments/assets/d5518c8d-ca37-4f28-aceb-0c5b31c76168)

Tertiary: In the account settings page is a option to set the client preference but it don't save the changes. Neither exists in the database a colum that could save the "SHOCKWAVE" or "FLASH" enum.
Maybe the SHOCKWAVE could be set to the default
![grafik](https://github.com/user-attachments/assets/6966be5e-8821-41d6-90db-b34abb8aa5cd)

**Comment by Quackster** [comment]
Not an issue, they were never coded/implemented.

**Comment by Kaan2106** [comment]
On the prefered client, I can understand :), thats on us now 😄 
But will be a mod-tool update released, since its not useable in flash?

**Comment by Quackster** [comment]
The only work I do on Havana is critical fixes now, I don't plan to do any more feature updates.
