### ISSUE TITLE
Unable to login again after registration

### ISSUE THREAD

**Issue by thychubbz** [Quackster/Havana#9]
After registering, I am able to login to the game and play. Once I log out and have to login again, the page will simply refresh. If I get the password wrong it will tell me, however with the correct password it will just refresh the page and ask me to login again. I am running release 4abba6a.

I have checked the server and web server logs, however there are no changes to be seen. 

To replicate: Fresh DB, Fresh Server install, register, log out, log in.

**Comment by SynologyCH** [comment]
I have the same problem, can someone help?
